"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { RefreshCw } from "lucide-react";
import { getLiveDriver,getLivePitWall,getLiveRace,getLiveStatus } from "@/lib/api/live";
import { getRaceControl,getWeather } from "@/lib/api/weekend";
import type { CurrentPitWall,LiveRace,LiveStatus,RaceControlResponse,WeatherResponse } from "@/lib/api/types";
import { driverCode,fmtNumber,fmtTime } from "@/lib/format";
import { EmptyRow,Status } from "./status";

export interface LivePitWallProps{initialStatus:LiveStatus;initialRace?:LiveRace|null;initialPitwall?:CurrentPitWall|null;initialWeather?:WeatherResponse|null;initialControl?:RaceControlResponse|null;driverLoader?:(id:string)=>Promise<CurrentPitWall>}

export function LivePitWall({initialStatus,initialRace=null,initialPitwall=null,initialWeather=null,initialControl=null,driverLoader=getLiveDriver}:LivePitWallProps){
 const [status,setStatus]=useState(initialStatus),[race,setRace]=useState(initialRace),[pitwall,setPitwall]=useState(initialPitwall),[weather,setWeather]=useState(initialWeather),[control,setControl]=useState(initialControl);
 const [selected,setSelected]=useState(initialPitwall?.snapshot?.drivers[0]?.driver.id??null),[detail,setDetail]=useState<CurrentPitWall|null>(null),[loading,setLoading]=useState(false),[refreshing,setRefreshing]=useState(false),[error,setError]=useState<string|null>(null);
 const refresh=useCallback(async()=>{if(document.hidden)return;setRefreshing(true);try{const s=await getLiveStatus();setStatus(s);if(s.live){const all=await Promise.allSettled([getLiveRace(),getLivePitWall(),getWeather(),getRaceControl()]);if(all[0].status==="fulfilled")setRace(all[0].value);if(all[1].status==="fulfilled")setPitwall(all[1].value);if(all[2].status==="fulfilled")setWeather(all[2].value);if(all[3].status==="fulfilled")setControl(all[3].value)}setError(null)}catch(e){setError(e instanceof Error?e.message:"Refresh failed")}finally{setRefreshing(false)}},[]);
 useEffect(()=>{let stopped=false,timer:ReturnType<typeof setTimeout>;const tick=async()=>{await refresh();if(!stopped)timer=setTimeout(tick,status.live?10000:30000)};timer=setTimeout(tick,status.live?10000:15000);return()=>{stopped=true;clearTimeout(timer)}},[refresh,status.live]);
 const selectDriver=useCallback((id:string)=>{setSelected(id);setDetail(null);setLoading(true);driverLoader(id).then(setDetail).catch(e=>setError(e instanceof Error?e.message:"Driver analysis unavailable")).finally(()=>setLoading(false))},[driverLoader]);
 const rows=pitwall?.snapshot?.drivers??[]; const raceById=useMemo(()=>new Map((race?.drivers??[]).map(x=>[x.driver.id,x])),[race?.drivers]); const chosen=detail?.driver??rows.find(x=>x.driver.id===selected)??null; const state=detail?.current_state??(selected?raceById.get(selected):null)??null;
 const selectedAlerts=useMemo(()=>chosen?.alerts??[],[chosen]);
 if(!status.live)return <div className="page"><header className="pitwall-bar"><div><span className="eyeline">Live pit wall</span><h1>Session offline</h1></div><Status value={status.session_status}/><button className="icon-button" onClick={refresh} disabled={refreshing}><RefreshCw size={15}/>{refreshing?"Refreshing":"Refresh"}</button></header><section className="offline-state"><span className="experimental">Strategy · experimental</span><h2>{status.next_session?.session.name??"No live timing feed"}</h2><p>{status.reason??"Live strategy analysis activates when the provider reports an active session."}</p>{status.next_session&&<div className="offline-next"><span>Next session</span><strong>{status.next_session.event.name}</strong><time>{fmtTime(status.next_session.session.start)}</time></div>}<div className="offline-actions"><Link className="button-link" href="/weekend">View weekend</Link><span>Recent race data · {status.availability.replaceAll("_"," ")}</span></div><div className="freshness-line"><Status value={status.freshness.state}/><span>Source · {status.provider}</span><span>Updated · {fmtTime(status.freshness.retrieved_at)}</span></div></section></div>;
 return <div className="page pitwall-page"><header className="pitwall-bar"><div><span className="eyeline">Live pit wall · {status.event?.name}</span><h1>{status.session?.name??"Live session"}</h1></div><div className="race-context"><Status value={status.session_status}/><span>Lap {pitwall?.snapshot?.lap??race?.lap??"—"}</span><Status value={pitwall?.data_freshness.state??status.freshness.state}/></div><button className="icon-button" onClick={refresh} disabled={refreshing}><RefreshCw size={15}/>{refreshing?"Refreshing":"Refresh"}</button></header>
 {error&&<div className="inline-alert" role="alert">Refresh issue · {error}</div>}{pitwall?.missing_requirements.length?<div className="inline-alert">Partial analysis · {pitwall.missing_requirements.join(" · ")}</div>:null}
 <div className="pitwall-layout"><section className="field-panel"><div className="section-header"><h2>Running order</h2><span>{rows.length} cars</span></div>{rows.length?<div className="field-list" role="listbox" aria-label="Drivers">{rows.map(x=>{const live=raceById.get(x.driver.id);return <button role="option" aria-selected={x.driver.id===selected} onClick={()=>selectDriver(x.driver.id)} className={`driver-row ${x.driver.id===selected?"selected":""}`} key={x.driver.id}><span className="position">{x.current_position??"—"}</span><b>{driverCode(x.driver)}</b><span className="team-cell">{live?.constructor?.name??"—"}</span><span className={`compound compound-${(x.compound??"").toLowerCase()}`}>{x.compound?.slice(0,1)??"—"}</span><span className="tyre-age">L{x.tyre_age??"—"}</span><span className="pit-count">PIT {live?.pit_stops_completed??"—"}</span><span className="gap">{x.gap_kind==="LAP_DEFICIT"?`+${x.laps_behind}L`:x.gap_to_leader_seconds==null?"—":`+${fmtNumber(x.gap_to_leader_seconds)}s`}</span><span className={`decision decision-${x.decision_state.toLowerCase()}`}>{x.recommendation??x.decision_state}</span></button>})}</div>:<EmptyRow>Live field analysis is not available.</EmptyRow>}</section>
 <section className="driver-panel" aria-live="polite">{loading&&!chosen?<div className="loading-shell">Loading driver analysis…</div>:chosen?<><div className="driver-head"><div><span className="eyeline">Selected driver</span><h2><span>{chosen.current_position??state?.position??"—"}</span>{chosen.driver.full_name}</h2><p>{state?.constructor?.name??"Constructor unavailable"} · {chosen.status}</p></div><span className="experimental">Strategy · experimental</span></div><dl className="metric-grid driver-metrics"><div><dt>Position</dt><dd>P{chosen.current_position??state?.position??"—"}</dd></div><div><dt>Compound</dt><dd>{chosen.compound??"—"}</dd></div><div><dt>Tyre age</dt><dd>{chosen.tyre_age??"—"} laps</dd></div><div><dt>Stint</dt><dd>{state?.stint_number??"—"}</dd></div><div><dt>Recent pace</dt><dd>{fmtNumber(chosen.recent_pace_seconds_per_lap)}s</dd></div><div><dt>Pit stops</dt><dd>{state?.pit_stops_completed??"—"}</dd></div><div><dt>Traffic</dt><dd>{chosen.traffic}</dd></div><div><dt>Pit cycle</dt><dd>P{chosen.pit_cycle_position??"—"}</dd></div></dl><div className="recommendation"><span className="eyeline">Pit wall call · {chosen.decision_state.replaceAll("_"," ")}</span><strong>{chosen.recommendation??"Insufficient data"}</strong><p>{chosen.main_opportunity??chosen.main_risk??"The model has not returned a strategic explanation."}</p>{chosen.alternative&&<small>Alternative · {chosen.alternative}</small>}</div>{chosen.paired_comparison?<div className="outcomes"><div className="section-header"><h2>Paired outcomes</h2><span>80% interval</span></div>{chosen.paired_comparison.outcomes.map(o=><div className="outcome" key={o.horizon_laps}><b>{o.horizon_laps} lap{o.horizon_laps>1?"s":""}</b><span>Median {fmtNumber(o.median_time_delta_seconds)}s</span><span>Pit {o.pit_net_position_range_80?.join(" to ")??"—"}</span><span>Extend {o.extend_net_position_range_80?.join(" to ")??"—"}</span></div>)}</div>:<EmptyRow>Paired scenario ranges are unavailable.</EmptyRow>}<div className="alerts"><div className="section-header"><h2>Driver alerts</h2></div>{selectedAlerts.length?selectedAlerts.map((a,i)=><p key={`${a.kind}-${i}`}><b>{a.kind}</b>{a.detail}</p>):<EmptyRow>No active alerts.</EmptyRow>}</div></>:<EmptyRow>Select a driver to inspect.</EmptyRow>}</section>
 <aside className="info-rail"><section><div className="section-header"><h2>Weather</h2>{weather&&<Status value={weather.freshness.state}/>}</div>{weather?.weather?<dl className="rail-metrics"><div><dt>Track</dt><dd>{weather.weather.track_temperature_c??"—"}°</dd></div><div><dt>Air</dt><dd>{weather.weather.air_temperature_c??"—"}°</dd></div><div><dt>Rain</dt><dd>{weather.weather.rainfall?"Yes":"No"}</dd></div></dl>:<EmptyRow>Unavailable</EmptyRow>}</section><section><div className="section-header"><h2>Race control</h2></div>{control?.messages.length?<ul className="rail-control">{control.messages.slice(0,6).map((m,i)=><li key={i}><b>{m.flag??m.category??"INFO"}</b><span>{m.message}</span></li>)}</ul>:<EmptyRow>No messages</EmptyRow>}</section><section><div className="section-header"><h2>Global alerts</h2></div>{pitwall?.snapshot?.alerts.length?<ul className="rail-control">{pitwall.snapshot.alerts.slice(0,6).map((a,i)=><li key={i}><b>{a.kind}</b><span>{a.detail}</span></li>)}</ul>:<EmptyRow>No alerts</EmptyRow>}</section></aside></div></div>;
}
