"""Abstraction implemented by any current-session timing source."""

from typing import Protocol

from f1_pitwall.domain.live import LiveSession


class LiveTimingProvider(Protocol):
    name: str

    async def get_current_session(self) -> LiveSession | None: ...

    async def get_drivers(self, session_key: int) -> list[dict]: ...

    async def get_positions(self, session_key: int) -> list[dict]: ...

    async def get_intervals(self, session_key: int) -> list[dict]: ...

    async def get_laps(self, session_key: int) -> list[dict]: ...

    async def get_stints(self, session_key: int) -> list[dict]: ...

    async def get_pit_stops(self, session_key: int) -> list[dict]: ...

    async def get_track_status(self, session_key: int) -> list[dict]: ...

    async def get_weather(self, session_key: int) -> list[dict]: ...

    async def get_race_control(self, session_key: int) -> list[dict]: ...

    async def get_session_results(
        self, session_key: int | None = None, meeting_key: int | None = None
    ) -> list[dict]: ...
