import { EmptyRow, Status, SurfaceError } from "@/components/status";
import { SessionTimeline } from "@/components/session-timeline";
import { getWeekend, getWeather, getRaceControl } from "@/lib/api/weekend";
import { fmtTime } from "@/lib/format";
export const dynamic="force-dynamic";
export default async function WeekendPage(){
 const [w,weather,control]=await Promise.allSettled([getWeekend(),getWeather(),getRaceControl()]);
 if(w.status==="rejected") return <div className="page"><SurfaceError title="Weekend unavailable" detail={w.reason instanceof Error?w.reason.message:undefined}/></div>;
 const d=w.value, wx=weather.status==="fulfilled"?weather.value:null, rc=control.status==="fulfilled"?control.value:null;
 return <div className="page"><header className="page-head"><div><span className="eyeline">Race weekend</span><h1>{d.event?.name??"Current weekend"}</h1><p>{d.circuit}{d.country?`, ${d.country}`:""} · Round {d.round??"—"} · {d.weekend_format}</p></div><Status value={d.status}/></header>
 <section className="section"><div className="section-header"><h2>Session sequence</h2>{d.next_session&&<span className="session-time">Next · {d.next_session.session.name} · {fmtTime(d.next_session.session.start)}</span>}</div>{d.session_schedule.length?<SessionTimeline sessions={d.session_schedule}/>:<EmptyRow>Schedule unavailable.</EmptyRow>}</section>
 <div className="weekend-grid"><section><div className="section-header"><h2>Qualifying</h2></div>{d.qualifying.length?<div className="table-scroll"><table><thead><tr><th>Pos</th><th>Driver</th><th>Q1</th><th>Q2</th><th>Q3</th></tr></thead><tbody>{d.qualifying.map(x=><tr key={x.driver.id}><td>{x.position??"—"}</td><td><b>{x.driver.code??x.driver.last_name}</b></td><td>{x.q1??"—"}</td><td>{x.q2??"—"}</td><td>{x.q3??"—"}</td></tr>)}</tbody></table></div>:<EmptyRow>Qualifying has not been published.</EmptyRow>}</section>
 <section><div className="section-header"><h2>Starting grid</h2></div>{d.grid.length?<div className="table-scroll"><table><thead><tr><th>Pos</th><th>Driver</th><th>Constructor</th></tr></thead><tbody>{d.grid.map(x=><tr key={x.driver.id}><td>{x.position??(x.pit_lane?"PL":"—")}</td><td><b>{x.driver.code??x.driver.last_name}</b></td><td>{x.constructor?.name??"—"}</td></tr>)}</tbody></table></div>:<EmptyRow>Grid not yet confirmed.</EmptyRow>}</section>
 <section className="weekend-wide"><div className="section-header"><h2>Latest session result</h2></div>{d.latest_results.length?<div className="table-scroll"><table><thead><tr><th>Pos</th><th>Driver</th><th>Constructor</th><th>Grid</th><th>Laps</th><th>Status / time</th><th className="numeric">Pts</th></tr></thead><tbody>{d.latest_results.map(x=><tr key={x.driver.id}><td>{x.position_text??x.position??"—"}</td><td><b>{x.driver.code??x.driver.last_name}</b></td><td>{x.constructor.name}</td><td>{x.grid??"—"}</td><td>{x.laps??"—"}</td><td>{x.time??x.status??"—"}</td><td className="numeric">{x.points??"—"}</td></tr>)}</tbody></table></div>:<EmptyRow>No completed session result is available.</EmptyRow>}</section></div>
 <div className="info-grid"><section><div className="section-header"><h2>Weather</h2>{wx&&<Status value={wx.freshness.state}/>}</div>{wx?.available&&wx.weather?<dl className="metric-grid"><div><dt>Air</dt><dd>{wx.weather.air_temperature_c??"—"}°C</dd></div><div><dt>Track</dt><dd>{wx.weather.track_temperature_c??"—"}°C</dd></div><div><dt>Humidity</dt><dd>{wx.weather.humidity_percent??"—"}%</dd></div><div><dt>Wind</dt><dd>{wx.weather.wind_speed??"—"}</dd></div></dl>:<EmptyRow>{wx?.reason??"Weather unavailable."}</EmptyRow>}</section>
 <section><div className="section-header"><h2>Race control</h2>{rc&&<Status value={rc.freshness.state}/>}</div>{rc?.messages.length?<ul className="control-list">{rc.messages.slice(0,8).map((m,i)=><li key={`${m.timestamp}-${i}`}><span>{m.category??m.flag??"NOTICE"}</span><p>{m.message??"—"}</p></li>)}</ul>:<EmptyRow>{rc?.reason??"No race control messages."}</EmptyRow>}</section></div></div>;
}
